name: audio_box_example
description: Example project using audio_box
publish_to: "none"

version: 1.0.0

environment:
  sdk: ^3.7.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  audio_box:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/bgm/
    - assets/bgs/
    - assets/se/
